# Generated by Django 4.2.19 on 2025-03-01 04:03

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.models.statuses
import nautobot_igp_models.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0062_module_data_migration'),
        ('extras', '0114_computedfield_grouping'),
        ('ipam', '0047_alter_ipaddress_role_alter_ipaddress_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGPRoutingInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('protocol', models.CharField(max_length=4)),
                ('isis_area', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="ISIS Area must be in the format '49', '49.0001', etc., with 1-7 segments of 1-4 digits each.", regex='^(\\d{1,4})(\\.\\d{1,4}){0,6}$'), nautobot_igp_models.models.validate_isis_area])),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='igp_routing_instances', to='dcim.device')),
                ('router_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ipam.ipaddress')),
                ('status', nautobot.extras.models.statuses.StatusField(null=True, on_delete=django.db.models.deletion.PROTECT, to='extras.status')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('vrf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='igp_routing_instances', to='ipam.vrf')),
            ],
            options={
                'verbose_name': 'IGP Routing Instance',
                'verbose_name_plural': 'IGP Routing Instances',
                'ordering': ['name'],
                'unique_together': {('name', 'device')},
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
