# Generated by Django 4.2.19 on 2025-02-28 21:10

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.models.statuses
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0114_computedfield_grouping'),
        ('dcim', '0062_module_data_migration'),
        ('nautobot_igp_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ospfconfiguration',
            name='area',
        ),
        migrations.CreateModel(
            name='OSPFInterfaceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('area', models.CharField(max_length=15)),
                ('cost', models.PositiveIntegerField(default=1)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ospf_configurations', to='dcim.interface')),
                ('ospf_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_configurations', to='nautobot_igp_models.ospfconfiguration')),
                ('status', nautobot.extras.models.statuses.StatusField(on_delete=django.db.models.deletion.PROTECT, to='extras.status')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'OSPF Interface Configuration',
                'verbose_name_plural': 'OSPF Interface Configurations',
                'unique_together': {('ospf_config', 'interface')},
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ISISInterfaceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('circuit_type', models.CharField(default='L1L2', max_length=10)),
                ('metric', models.PositiveIntegerField(default=10)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isis_configurations', to='dcim.interface')),
                ('isis_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_configurations', to='nautobot_igp_models.isisconfiguration')),
                ('status', nautobot.extras.models.statuses.StatusField(on_delete=django.db.models.deletion.PROTECT, to='extras.status')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ISIS Interface Configuration',
                'verbose_name_plural': 'ISIS Interface Configurations',
                'unique_together': {('isis_config', 'interface')},
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
