# Generated by Django 4.2.19 on 2025-03-02 03:19

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.models.statuses
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0062_module_data_migration'),
        ('ipam', '0047_alter_ipaddress_role_alter_ipaddress_status_and_more'),
        ('extras', '0114_computedfield_grouping'),
        ('nautobot_igp_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='igproutinginstance',
            unique_together={('device', 'protocol', 'vrf')},
        ),
        migrations.CreateModel(
            name='ISISConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('system_id', models.CharField(max_length=19, unique=True)),
                ('instance', models.ForeignKey(limit_choices_to={'protocol': 'ISIS'}, on_delete=django.db.models.deletion.CASCADE, related_name='isis_configurations', to='nautobot_igp_models.igproutinginstance')),
                ('status', nautobot.extras.models.statuses.StatusField(null=True, on_delete=django.db.models.deletion.PROTECT, to='extras.status')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ISIS Configuration',
                'verbose_name_plural': 'ISIS Configurations',
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ISISInterfaceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('circuit_type', models.CharField(default='L1L2', max_length=10)),
                ('metric', models.PositiveIntegerField(default=10)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isis_configurations', to='dcim.interface')),
                ('isis_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_configurations', to='nautobot_igp_models.isisconfiguration')),
                ('status', nautobot.extras.models.statuses.StatusField(null=True, on_delete=django.db.models.deletion.PROTECT, to='extras.status')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ISIS Interface Configuration',
                'verbose_name_plural': 'ISIS Interface Configurations',
                'unique_together': {('isis_config', 'interface')},
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
