# Generated by Django 4.2.28 on 2026-02-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_igp_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='isisconfiguration',
            name='default_hello_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisconfiguration',
            name='default_hello_multiplier',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisconfiguration',
            name='default_metric',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisconfiguration',
            name='default_priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ospfconfiguration',
            name='default_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ospfconfiguration',
            name='default_dead_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ospfconfiguration',
            name='default_hello_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ospfconfiguration',
            name='default_priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='isisinterfaceconfiguration',
            name='metric',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ospfinterfaceconfiguration',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
